### ISSUE TITLE
Google Play purchases are not supported in your country

### ISSUE THREAD

**Issue by imKota** [ClaudiuGeorgiu/PlaystoreDownloader#2]
```
➜  python3 download.py com.symudolcreadigol.prosiectx
12/09/2017 02:57:18> [ERROR][download()] Error for app "com.symudolcreadigol.prosiectx": Google Play purchases are not supported in your country. Unfortunately you will not be able to complete purchases.
Error when downloading "com.symudolcreadigol.prosiectx".
```

**Comment by ClaudiuGeorgiu** [comment]
Hi, thanks for submitting the issue. Are you able to download this app directly using your android device? I've seen this error before with some apps, but I think this is related to the account rather than to the download script. When I encounter this kind of errors, I'm not able to download the app even if I use a real android device. I suppose the only way to download this kind of apps is to create an account in the same country where the developer published the app, maybe using a VPN.

**Comment by imKota** [comment]
@ClaudiuGeorgiu Thanks for the quick response!
Tomorrow I'll try to register an account via VPN, and try to download the application.
