### ISSUE TITLE
Some game can't get version from app_details method

### ISSUE THREAD

**Issue by MrLuoXuan** [ClaudiuGeorgiu/PlaystoreDownloader#27]
some game can't version and file size from app_details method result docV2 attribute.
For example:
     game_id jp.konami.bm2dxum
     google play url: https://play.google.com/store/apps/details?id=jp.konami.bm2dxum
     can display all information in browser, but can't get version information from google play interface.
     what can i do to fix this problem.

**Comment by ClaudiuGeorgiu** [comment]
Hi, sorry for the very late reply. Are you still having this issue with the latest version of the tool? In that case please provide the exact command you're using and the error/stack trace. Are you able to install the application directly into your device? Unfortunately I cannot test the app you indicated since it's not compatible with my devices.
