### ISSUE TITLE
Default shared/anonymous configuration to download app without giving auth details

### ISSUE THREAD

**Issue by emanuelb** [ClaudiuGeorgiu/PlaystoreDownloader#56]
### Is this feature request related to a problem?

Using this tool require manual configuration of ANDROIDID and inserting authentication data (EMAIL+PASSWORD) to google

### Proposed solution

Anonymous mode that use shared account can be used, see for example other projects that implement this:
gplaycli: https://github.com/matlink/gplaycli

> By default, gplaycli fetches a token from a token dispenser server located at https://matlink.fr/token/ to login in Google Play.

AuroraStore app:
https://gitlab.com/AuroraOSS/AuroraStore https://github.com/yeriomin/YalpStore
> Anonymous accounts — You can log in and download with anonymous accounts so you don't have to use your own account

YalpStore app:
> By default Yalp Store connects to Google services using a built-in account, so you do not have to own a Google account to use it

### Would you like to submit a pull request for this feature?

No

**Comment by ClaudiuGeorgiu** [comment]
Hi @emanuelb, thanks for the suggestion, but currently this is not a feature I'm interested in adding.

The purpose of this tool is to provide an easier way to download apks files: instead of using your device, downloading the app and then copying the app from the device's storage, you can directly download the app on the computer by using this tool (PlaystoreDownloader tries to emulate the device's behavior when downloading an apk, that's why manual configuration is needed).

Adding the possibility to download apks anonymously would mean that someone has to: create one ore more Google accounts, configure those accounts with devices that are able to download apks and make the auth tokens available to everyone. So, what happens if someone wants to download an apk that is not available for any of those shared accounts? What happens if the shared accounts get locked for some reasons? And so on... Sorry, but it's not something I want to deal with.

However, if you need the anonymous download feature, the other tools mentioned in your message should be valid alternatives, so please use one of them 👍.

**Comment by emanuelb** [comment]
The problem is that gpalycli doesn't work for me due to bug: https://github.com/matlink/gplaycli/issues/280#issuecomment-853462981
and the other solutions are android apps, while I am looking for CLI/GUI tool for linux to download apks as this project does, thus opened this issue and issue like this one for apk downloader projects that don't have anonymous download feature, the mentioned OSS projects are for contributors to look how this was implemented.

**Comment by d78ui98** [comment]
@emanuelb did you find any solutions or workaround for this?
