### ISSUE TITLE
Login failed, please check your credentials

### ISSUE THREAD

**Issue by muzzyrost** [ClaudiuGeorgiu/PlaystoreDownloader#61]
Hello there!

Yesterday it starts showing error message from when I try to download an app from the Google Play Store:

`[WARNING][playstore.util][wrapped()] Login failed, please check your credentials`

I tried the following:
- different accounts
- account password without MFA
- account password without MFA and "unsecure" connection enabled (or however that is called)
- app-specific password (with MFA)

**Comment by druphliu** [comment]
I have the same question! I use the app-specific password,it show me this:
Error=BadAuthentication
Info=WebLoginRequired
Url=https://accounts.google.com/signin/continue?sarp=1&scc=1&continue=https://accounts.google.com/o/android/auth?****

**Comment by IdanStoremaven** [comment]
Any news?

**Comment by IdanStoremaven** [comment]
Also experiencing same issue, even with urllib3 = "<1.26.0"

**Comment by wxqqh** [comment]
> Found a solution for this issue by reading code from the Racoon project (https://github.com/onyxbits/raccoon4). Basically add `"sdk_version": "16"` to the `params` dictionary on file `playstore.py` so that it looks like this:
> 
> ```python
>         params = {
>             "Email": self.email,
>             "EncryptedPasswd": self.encrypted_password,
>             "service": "androidmarket",
>             "accountType": "HOSTED_OR_GOOGLE",
>             "has_permission": 1,
>             "source": "android",
>             "device_country": self.lang,
>             "lang": self.lang,
>             "sdk_version": "16" 
>         }
> ```
> 
> It worked fine for me after adding this.

I had modified according to the above, but the problem remains

**Comment by 89z** [comment]
I have an alternate tool that works:

~~~
PS C:\> googleplay -a org.videolan.vlc -v 13040204
&{Status:1 AppDeliveryData:{DownloadURL:https://play.googleapis.com/download/by-token/download?token=AOTCm0RYTPz_Epkcgjkk7t54--gVIxs_On7L0xAdAcqfCON6JVQA0KWOeG4OXMfYg5-GFuxC093gV6pUVuPL0MvzD6VSRHZmzUeGcYfpdSGGrGQGt2oP6Kn6srx2UuvLtKH5_sZJcA4xKN_D0BX-QRgcIvzkJpe-DjgosXKPRQTAByYv4SC6-x7WSiX66WeQg4t0xF-DFke9OeXuQDityXrfQTXGsRudpWKJOYLjOEPBV9xL4Q-ROxwCuTyKzZEaBPDHjJrsxKHLWIWsIhhxJbXk_Kl_EdnGfoVNYPBK87HZWmTj60DEL9dgjbo_4M-C7vdzEZO7f6D23FH89OLP4iZ2mCEWUb6OZzsbdlM3IcfRqVi0r7GSDqK4kopyGLzBWu2VwDGaTEG3DHIh0_6IQcznvs4&cpn=swe5gibpv_wri67X&server=boq}}
~~~

https://github.com/89z/googleplay

**Comment by ClaudiuGeorgiu** [comment]
> I have an alternate tool that works:
> 
> ```
> PS C:\> googleplay -a org.videolan.vlc -v 13040204
> &{Status:1 AppDeliveryData:{DownloadURL:...}}
> ```
> 
> https://github.com/89z/googleplay

This tool works too (at least with my testing account):
```
C:\Users\user\Desktop\PlaystoreDownloader>pipenv run python3 -m playstoredownloader.cli org.videolan.vlc
Downloading org.videolan.vlc:  46%|█████████████████                        |[00:01<00:02, 8711.76 KB/s]
```
Issues arise when using different accounts/devices to download applications. This is a common issue among the projects for downloading apps from the Play Store: everything works fine for the author, but other people using the project get login/download errors that cannot always be replicated. However, I'm glad you found a solution that works for you 😉.

**Comment by 89z** [comment]
> This tool works too (at least with my testing account):

@ClaudiuGeorgiu with all due respect, saying "it works for me" is not totally helpful. If you didnt notice, this issue is being reported over and over:

- https://github.com/ClaudiuGeorgiu/PlaystoreDownloader/issues/57
- https://github.com/ClaudiuGeorgiu/PlaystoreDownloader/issues/55
- https://github.com/ClaudiuGeorgiu/PlaystoreDownloader/issues/49
- https://github.com/ClaudiuGeorgiu/PlaystoreDownloader/issues/46
- https://github.com/ClaudiuGeorgiu/PlaystoreDownloader/issues/43

so it seems that you are satisfied that it works for your account, and are not concerned with the other people having trouble. This is why I created my own tool, since it appears you are not taking the problem seriously. If that is not the case I apologize, but thats how I perceive your actions (or lack of). My tool works for certain, and I am willing to troubleshoot if my tool does not work for someone, as I now have a detailed knowledge of the login and device process.

**Comment by ClaudiuGeorgiu** [comment]
Hi @89z, as I wrote earlier I'm happy that you found a solution (by writing your own tool). You're right, I'm satisfied with how the tool works for me and I'm sorry if it doesn't work for everyone, but I don't have a universal fix for this issue.

**Comment by 89z** [comment]
I finally found the fix to this. Despite the comments saying it didnt help [1][2], the fix is already given in this thread [3]. You need to modify this:

https://github.com/ClaudiuGeorgiu/PlaystoreDownloader/blob/58a74a9ab2749f932c32bc8204a3a323d115629e/playstoredownloader/playstore/playstore.py#L122-L131

and add this at the end:

~~~py
"sdk_version": "16" 
~~~

You dont need to do "allow less secure apps". You do need to make sure to input the GSF ID (in hex form) to the credentials file.


1. https://github.com/ClaudiuGeorgiu/PlaystoreDownloader/issues/61#issuecomment-947612767
2. https://github.com/ClaudiuGeorgiu/PlaystoreDownloader/issues/61#issuecomment-950138676
3. https://github.com/ClaudiuGeorgiu/PlaystoreDownloader/issues/61#issuecomment-937729685

**Comment by 89z** [comment]
https://github.com/ClaudiuGeorgiu/PlaystoreDownloader/issues/83
