### ISSUE TITLE
Certificate verify failed: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by anthonyalayo** [ClaudiuGeorgiu/PlaystoreDownloader#77]
Hey there,

I wanted to start out by saying great work on this project. I was curious how some websites are able to grab Android applications straight from the play store programatically.

Curious about the flow of requests, I hooked up Charles Proxy (MITM) before running the downloader CLI. Unfortunately, I'm seeing this error:

```
Max retries exceeded with url: /auth (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))
```

Is there any way to view the traffic coming from this script? 

Thanks,
Anthony

**Comment by 89z** [comment]
Even if this worked, and even if you captured every single request perfectly, it wouldn't get you all the way. The Google Play server (`android.googleapis.com` and others) uses TLS fingerprinting [1], so in addition to sending a correct token and device ID, you must also send a correct TLS client hello.

Otherwise the server will reject the request with `BadAuthentication`. This package avoids that problem by using an old `urllib3`:

https://github.com/ClaudiuGeorgiu/PlaystoreDownloader/blob/58a74a9ab2749f932c32bc8204a3a323d115629e/Pipfile#L12

instead of actually implemented a proper hello [2].

1. https://github.com/89z/googleplay/blob/v1.9.0/play.go#L100-L105
2. https://github.com/simon-weber/gpsoauth

**Comment by anthonyalayo** [comment]
@89z thanks for explaining! I was unaware of TLS fingerprint block lists until today. :-)

I went down the rabbit hole here. I'm guessing urllib3 <1.26.0 works because its fingerprint happens to collide with a large enough percentage of good traffic.

At the moment, since most programming libraries don't allow configuration of the parameters that get fingerprinted, most tools can't get around it either: https://httptoolkit.tech/blog/tls-fingerprinting-node-js/

Looks like there is an active discussion here about it:
https://github.com/httptoolkit/httptoolkit/issues/256

**Comment by 89z** [comment]
whats your goal here? Are you wanting to implement your own package?

**Comment by anthonyalayo** [comment]
@89z no goal honestly, I was just curious to know how it works / how the maintainers keep the project running. I setup an Android emulator running Marshmallow and hooked it up to Charles and I was able to see requests to the Play Store, but how the request flow worked was muddy. I used Marshmallow since it was the last OS version before they started enforcing HTTPS. I have a hobby of seeing how things work. :-)

**Comment by 89z** [comment]
Well this space does have room for improvement, if you are interested in starting your own project. No one seems to have figured out app version history yet. Also no one has figured out how to disable the device check with app requests either. So if you could figure out either of those, it would be quite helpful.
