### ISSUE TITLE
Is it possible to add Multiple credentials?

### ISSUE THREAD

**Issue by Croodo** [ClaudiuGeorgiu/PlaystoreDownloader#81]
Is it possible to add **multiple credentials** file or json array , which have to work randomly when run the program. 
Actually i want to download multiple apk by running it with an api request which gonna hold **upto 100 apps**. 

Random (multiple) credentials required to stay unban from google.

**Comment by adtimizer** [comment]
@Croodo are you able to run it with single credential? for the past 4 days there is an issue with login to playstore api. are you not facing it?

**Comment by Croodo** [comment]
Nop can’t fetch ,  login failed , didn’t noticed that before. 😑

**Comment by ClaudiuGeorgiu** [comment]
> Is it possible to add **multiple credentials** file or json array , which have to work randomly when run the program.

Currently it's not implemented, but it could be a good enhancement. The [json configuration file](https://github.com/ClaudiuGeorgiu/PlaystoreDownloader/blob/58a74a9ab2749f932c32bc8204a3a323d115629e/credentials.json) is already an array, but currently contains only one credential. I think you could add more credentials to the json configuration and then change this line of code to take a random credential from the list (instead of the first one):

https://github.com/ClaudiuGeorgiu/PlaystoreDownloader/blob/58a74a9ab2749f932c32bc8204a3a323d115629e/playstoredownloader/playstore/playstore.py#L112

**Comment by adtimizer** [comment]
Hello Gabriel,
Thanks for the tip. I guess you are aware that i the past few days there is an issue with anything related to login on the gplayapi. 
Are you able to login? can you please help with that?

**Comment by ClaudiuGeorgiu** [comment]
> I guess you are aware that i the past few days there is an issue with anything related to login

I just tried and I confirm that login is not working also for me. I'm sorry, but I don't have a solution and I don't think I will be able to spend time working on this issue in the near future.
